ks45team01/src/main/java/ks45team01/controller/AdminWorkController.java
ks45team01/src/main/java/ks45team01/controller/DepartWorkController.java
ks45team01/src/main/java/ks45team01/controller/MessengerController.java
ks45team01/src/main/java/ks45team01/controller/WorkController.java
ks45team01/src/main/resources/templates/fragments/sideBar.html
ks45team01/src/main/resources/templates/messenger/messenger_chat_detail.html
ks45team01/src/main/resources/templates/messenger/messenger_chat_insert.html
ks45team01/src/main/resources/templates/messenger/messenger_chat_invite_insert.html
ks45team01/src/main/resources/templates/messenger/messenger_chat_list.html
ks45team01/src/main/resources/templates/messenger/messenger_worker_list.html
ks45team01/src/main/resources/templates/settings/vacation_insert.html
ks45team01/src/main/resources/templates/settings/vacation_variety_insert.html
ks45team01/src/main/resources/templates/settings/vacation_variety_list.html
ks45team01/src/main/resources/templates/settings/vacation_variety_modify.html
ks45team01/src/main/resources/templates/settings/work_type_insert.html
ks45team01/src/main/resources/templates/settings/work_type_list.html
ks45team01/src/main/resources/templates/settings/work_type_modify.html
ks45team01/src/main/resources/templates/vacation/vacation_info_all_list.html
ks45team01/src/main/resources/templates/vacation/vacation_info_department_list.html
ks45team01/src/main/resources/templates/vacation/vacation_info_list.html
ks45team01/src/main/resources/templates/work/work_all_list.html
ks45team01/src/main/resources/templates/work/work_authority_Insert.html
ks45team01/src/main/resources/templates/work/work_department_list.html
ks45team01/src/main/resources/templates/work/work_insert.html
ks45team01/src/main/resources/templates/work/work_list.html

side bar -근태, 메신저, 관리자 설정(근태)
controller
-adminwork, departwork,messenger,work

[team project]

---

ks45team01/src/main/java/ks45team01/controller/FormController.java
ks45team01/src/main/java/ks45team01/dto/FormBoard.java
ks45team01/src/main/java/ks45team01/mapper/FormBoardMapper.java
ks45team01/src/main/java/ks45team01/service/FormBoardService.java
ks45team01/src/main/resources/application.properties
ks45team01/src/main/resources/mapper/FormBoardMapper.xml
ks45team01/src/main/resources/templates/form/addForm.html
ks45team01/src/main/resources/templates/form/formList.html
ks45team01/src/main/resources/templates/form/formView.html

db접속정보 ks45team01로 수정하였습니다.
mapper 파일 위치 설정하였고, dto 패키지 설정했습니다.
bin이라는 중복 폴더 및 파일이 있어 삭제했습니다.

[project] formBoard 파일첨부 빼고 CR작업했습니다.

---

ks45team01/src/main/java/ks45team01/controller/projectController.java
ks45team01/src/main/resources/application.properties
ks45team01/src/main/resources/templates/project/project_board_insert.html
ks45team01/src/main/resources/templates/project/project_board_modify.html
ks45team01/src/main/resources/templates/project/project_detail.html
ks45team01/src/main/resources/templates/project/project_member_insert.html
ks45team01/src/main/resources/templates/project/project_member_modify.html
ks45team01/src/main/resources/templates/project/project_unit.html
ks45team01/src/main/resources/templates/project/project_unit_insert.html
ks45team01/src/main/resources/templates/project/project_unit_member_insert.html
ks45team01/src/main/resources/templates/project/project_unit_member_modify.html

[team01 jhw] 1.수정:projectController  2.추가:프로젝트화면들

---

ks45team01/src/main/java/ks45team01/controller/ApprovalController.java
ks45team01/src/main/resources/templates/fragments/sideBar.html

1. sidebar 결재 메뉴 주소 추가했습니다.
2. ApprovalController 주소 연결 했습니다.

[team01project rjy] 1. 수정 sidebar.html, ApprovalController.java

---

ks45team01/src/main/java/ks45team01/controller/CalenderController.java
ks45team01/src/main/resources/templates/calender/scheduel.html
ks45team01/src/main/resources/templates/fragments/sideBar.html

1.수정: sidebar, community controller,calender controller
추가: community, calender
2.파일 이름 : community, calender .html

[team01project jsh]

---

ks45team01/src/main/java/ks45team01/controller/AdminWorkController.java
ks45team01/src/main/java/ks45team01/dto/WorkType.java
ks45team01/src/main/java/ks45team01/mapper/WorkTypeMapper.java
ks45team01/src/main/java/ks45team01/service/WorkTypeService.java
ks45team01/src/main/resources/mapper/WorkTypeMapper.xml
ks45team01/src/main/resources/templates/fragments/sideBar.html
ks45team01/src/main/resources/templates/settings/work_type_list.html
ks45team01/src/main/resources/templates/work/work_all_list.html

1.수정- adminWorkController, work_all_list.html, work_type_list.html side bar
추가-WorkType.java(dto), WorkTypeMapper.xml,
WorkTypeMapper.java,WorkTypeService.java
2.무슨파일인지쓰기
수정 : adminWorkController- 관리자 근태 설정 컨트롤러(근무유형 조회 수정)
work_all_list.html - 전사원 근태 조회 화면
work_type_list.html - 근무형태 조회
side bar- 관리자설정 경로 절대경로로 수정
추가 : WorkType.java(dto) - 근무형태 dto
WorkTypeMapper.xml - 근무형태 mapper파일
WorkTypeMapper.java - 근무형태 mapper interface
WorkTypeService.java - 근무형태 서비스 파일

[team01project kjy]

---

ks45team01/src/main/java/ks45team01/controller/MemberController.java
ks45team01/src/main/resources/templates/member/member_delete.html
ks45team01/src/main/resources/templates/member/member_department_delete.html
ks45team01/src/main/resources/templates/member/member_department_insert.html
ks45team01/src/main/resources/templates/member/member_department_list.html
ks45team01/src/main/resources/templates/member/member_insert.html
ks45team01/src/main/resources/templates/member/member_level_insert.html
ks45team01/src/main/resources/templates/member/member_level_list.html
ks45team01/src/main/resources/templates/member/member_level_modify.html
ks45team01/src/main/resources/templates/member/member_modify.html
ks45team01/src/main/resources/templates/member/member_position_insert.html
ks45team01/src/main/resources/templates/member/member_position_list.html
ks45team01/src/main/resources/templates/member/member_position_modify.html

****			수정:memberController 경로 추가

[team01 jhw]추가:member_기타등등.html

---

ks45team01/src/main/java/ks45team01/dto/listMember.java
ks45team01/src/main/resources/mapper/MemberMapper.xml

[team1 jhw] 추가:dto listMember.java 추가

---

ks45team01/src/main/java/ks45team01/controller/ApprovalController.java
ks45team01/src/main/resources/application.properties
ks45team01/src/main/resources/log4jdbc.log4j2.properties
ks45team01/src/main/resources/logback-spring.xml
ks45team01/src/main/resources/templates/approval/approvalDoneList.html
ks45team01/src/main/resources/templates/approval/approvalList.html
ks45team01/src/main/resources/templates/approval/circularList.html
ks45team01/src/main/resources/templates/approval/draftInsert.html
ks45team01/src/main/resources/templates/approval/finalApproverList.html
ks45team01/src/main/resources/templates/approval/referrerList.html
ks45team01/src/main/resources/templates/approval/rejectList.html

application.properties
SQL문과 해당 SQL을 실행시키는데 수행된 시간 정보만 출력되게 프로퍼티 로그 작업했습니다. ApprovalController.java
결재 가상화면 주소 추가 했습니다.
나머지 전부 가상화면html 만들었습니다.

[team01project rjy] 1. 수정 2. 추가

---

ks45team01/src/main/java/ks45team01/controller/ApprovalController.java
ks45team01/src/main/resources/templates/approval/approvalDoneList.html
ks45team01/src/main/resources/templates/approval/approvalList.html
ks45team01/src/main/resources/templates/approval/circularList.html
ks45team01/src/main/resources/templates/approval/draftList.html
ks45team01/src/main/resources/templates/approval/finalApproverList.html
ks45team01/src/main/resources/templates/approval/receiverList.html
ks45team01/src/main/resources/templates/approval/rejectList.html
ks45team01/src/main/resources/templates/approval/vacationInsert.html
ks45team01/src/main/resources/templates/approval/workCorrectInsert.html
ks45team01/src/main/resources/templates/form/formList.html
ks45team01/src/main/resources/templates/fragments/sideBar.html

ApprovalController 휴가신청/근태정정신청 주소 연결했습니다.
sidebar.html 결재 메뉴 휴가신청, 근태정정신청 추가 했습니다.
vacationInsert/workCorrectInsert 가상 화면 만들었습니다.

[team01project rjy] 1. 수정, 2. 생성

---

ks45team01/src/main/java/ks45team01/controller/AdminEmploymentController.java
ks45team01/src/main/java/ks45team01/controller/AdminReservationController.java
ks45team01/src/main/java/ks45team01/controller/EmploymentController.java
ks45team01/src/main/java/ks45team01/controller/ReservationController.java
ks45team01/src/main/resources/templates/employment/annoucement_insert.html
ks45team01/src/main/resources/templates/fragments/sideBar.html
ks45team01/src/main/resources/templates/reservation/meetingroom_admin_list.html
ks45team01/src/main/resources/templates/reservation/meetingroom_insert.html
ks45team01/src/main/resources/templates/reservation/meetingroom_modify.html

수정:
AdminEmploymentController.java
AdminReservationController.java
annoucement_insert.html
EmploymentController.java
meetingroom_admin_list.html
meetingroom_insert.html
meetingroom_list.html
meetingroom_modify.html
ReservationController.java
sideBar.html

[team01project jmj]

---

ks45team01/src/main/resources/templates/approval/draftInsert.html

draftInsert.html 카테고리 네비바 추가했습니다.

[team01project rjy] 1. 수정

---

ks45team01/src/main/java/ks45team01/controller/MemberController.java
ks45team01/src/main/resources/templates/fragments/sideBar.html
ks45team01/src/main/resources/templates/member/member.html
ks45team01/src/main/resources/templates/member/member_modify.html
ks45team01/src/main/resources/templates/member/member_password_modify.html

추가:member_password_modify.html 비밀번호 변경홈페이지
변경:member.html 프론트 변경
member_modify.html 프론트 변경
sideBar.html 프론트및 경로 변경
MemberController.java password_modify.html 경로 추가

[team1 jhw]

---

ks45team01/src/main/java/ks45team01/controller/ApprovalController.java
ks45team01/src/main/resources/templates/approval/approvalDoneList.html
ks45team01/src/main/resources/templates/approval/approvalDoneView.html
ks45team01/src/main/resources/templates/approval/draftList.html
ks45team01/src/main/resources/templates/approval/draftView.html
ks45team01/src/main/resources/templates/approval/receiverList.html
ks45team01/src/main/resources/templates/approval/receiverView.html
ks45team01/src/main/resources/templates/fragments/infoBar.html

수정 결재완료리스트, 기안목록, 수신함리스트 상세화면 추가 및 수정했습니다.
추가 상세화면 페이지 작업완료했습니다.
수정(2) infobar 사진 깨져서 수정 작업했습니다.

[team01project rjy]

---

ks45team01/src/main/java/ks45team01/unity/worker/controller/MemberController.java
ks45team01/src/main/resources/templates/fragments/sideBar.html
ks45team01/src/main/resources/templates/member/memberAdmin.html

member/member.html
member/memberAdmin.html
controller/MemberController.java
fragments/sideBar.html

[사이드바 및 멤버.html 수정 jhw]

---

ks45team01/src/main/resources/static/assets/js/app.js
ks45team01/src/main/resources/templates/fragments/sideBar.html

app.js : active를 path값이 요청주소와 같으면 상위 부모 요소에 active 속성을 추가하도록
수정 하였습니다.

[project sideBar, app.js 수정 rjy] 1. 수정

---

ks45team01/src/main/resources/templates/member/memberAdmin.html
ks45team01/src/main/resources/templates/project/project.html

수정.
/member/memberAdmin.html
/project/project.html
화면수정

[멤버어드민 프로젝트 jhw]

---

ks45team01/src/main/resources/templates/fragments/sideBar.html
ks45team01/src/main/resources/templates/fragments/top.html

sideBar 정렬 및 결재, 파일 메뉴 추가했습니다.
top 메인페이지를 눌렀을 때 메인페이지로 갈 수 있도록 경로 설정 했습니다.

[project rjy] 1. 수정

---

ks45team01/src/main/resources/templates/layout/default.html
ks45team01/src/main/resources/templates/project/project.html
ks45team01/src/main/resources/templates/project/project_calender.html
ks45team01/src/main/resources/templates/project/project_detail.html
ks45team01/src/main/resources/templates/project/project_files.html
ks45team01/src/main/resources/templates/project/project_home.html
ks45team01/src/main/resources/templates/project/project_home/project_board_insert.html
ks45team01/src/main/resources/templates/project/project_home/project_calender_insert.html
ks45team01/src/main/resources/templates/project/project_home/project_task_insert.html
ks45team01/src/main/resources/templates/project/project_home/project_todo.html
ks45team01/src/main/resources/templates/project/project_task.html

폴더 및 화면수정
/project/project_home/project_calender_insert.html /project/project_home/project_task_insert.html
추가
/project/project_home/project_todo.html
/project/project_home.html
수정
/layout/default.html
/project/project.html
/project/project_detail.html
/project/project_files.html
/project/project_task.html

[디폴트 빈공간 제거 및 프로젝트 화면및 경로 수정 업데이트 jhw]

---

ks45team01/src/main/java/ks45team01/unity/dto/File.java
ks45team01/src/main/java/ks45team01/unity/mapper/FileMapper.java
ks45team01/src/main/java/ks45team01/unity/service/FileService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ApprovalController.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/FileController.java
ks45team01/src/main/resources/mapper/FileMapper.xml
ks45team01/src/main/resources/templates/approval/referrerList.html
ks45team01/src/main/resources/templates/approval/referrerView.html
ks45team01/src/main/resources/templates/file/addFile.html
ks45team01/src/main/resources/templates/file/fileList.html
ks45team01/src/main/resources/templates/file/fileUpdate.html
ks45team01/src/main/resources/templates/file/fileView.html
ks45team01/src/main/resources/templates/form/formList.html

수정
addFile.html -- 파일 등록 작업 완료했습니다.
ApprovalController.java
FileController.java
fileList.html -- 파일 목록 작업 완료했습니다.
fileUpdate.html -- 파일 등록 작업 완료했습니다.
fileView.html -- 파일 상세보기 작업 80% 완료했습니다.
referrerList.html
추가
referrerView.html -- 참조문서 상세보기 추가
FileService.java
FileMapper.xml
FileMapper.java
File.java -- dto 추가

[file관리 crud 적용 및 화면연결]

---

ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminEmploymentController.java
ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminReservationController.java
ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminWorkController.java
ks45team01/src/main/java/ks45team01/unity/dto/Work.java

controller 수정
AdminEmploymentController.java
AdminReservationController.java
AdminWorkController.java
dto 수정
Work.java

[controller 수정 및 dto 수정 kjy]

---

ks45team01/src/main/resources/templates/layout/default.html
ks45team01/src/main/resources/templates/project/project_detail.html
ks45team01/src/main/resources/templates/project/project_home.html
ks45team01/src/main/resources/templates/project/project_home/project_board_insert.html

수정
/layout/default.html
/project/project_home/project_board_insert.html
/project/project_detail.html
/project/project_home.html

[디폴트 자바스크립트 구역설정 및 프로젝트 화면 수정 jhw]

---

ks45team01/src/main/resources/templates/main.html

[근태 등록을 위한 javascript 생성 kjy]

---

ks45team01/src/main/java/ks45team01/unity/mapper/FileMapper.java
ks45team01/src/main/java/ks45team01/unity/mapper/FormBoardMapper.java
ks45team01/src/main/java/ks45team01/unity/service/FileService.java
ks45team01/src/main/java/ks45team01/unity/service/FormBoardService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/FileController.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/FormController.java
ks45team01/src/main/resources/mapper/FileMapper.xml
ks45team01/src/main/resources/mapper/FormBoardMapper.xml
ks45team01/src/main/resources/templates/file/hrList.html
ks45team01/src/main/resources/templates/form/formList.html
ks45team01/src/main/resources/templates/fragments/sideBar.html

수정
hrList.html -- 문서 이름 수정했습니다.
sideBar.html -- 파일 메뉴 뎁스 추가했습니다.
FileService.java -- 메서드 및 변수명 수정했습니다.
FileController.java -- 메서드 및 변수명 수정했습니다.

[파일 관리 카테고리별 네이밍 수정 rjy]

---

ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java
ks45team01/src/main/resources/static/assets/js/app.js
ks45team01/src/main/resources/templates/project/project_detail.html
ks45team01/src/main/resources/templates/project/project_home.html
ks45team01/src/main/resources/templates/project/project_home/project_board_insert.html
ks45team01/src/main/resources/templates/project/project_home/project_calender_insert.html
ks45team01/src/main/resources/templates/project/project_home/project_task_insert.html
ks45team01/src/main/resources/templates/project/project_home/project_todo.html

수정
ks45team01/src/main/resources/static/assets/js/app.js ks45team01/src/main/resources/templates/project/project_home/project_board_insert.html ks45team01/src/main/resources/templates/project/project_home/project_calender_insert.html ks45team01/src/main/resources/templates/project/project_detail.html ks45team01/src/main/resources/templates/project/project_home.html ks45team01/src/main/resources/templates/project/project_home/project_task_insert.html ks45team01/src/main/resources/templates/project/project_home/project_todo.html ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java

[프로젝트 화면수정 jhw]

---

ks45team01/src/main/java/ks45team01/unity/mapper/FileMapper.java
ks45team01/src/main/java/ks45team01/unity/service/FileService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/FileController.java
ks45team01/src/main/resources/mapper/FileMapper.xml
ks45team01/src/main/resources/templates/file/marketingList.html
ks45team01/src/main/resources/templates/fragments/sideBar.html

수정
FileController.java -- 마케팅 화면 연결 완료했습니다.
FileMapper.java -- 마케팅 파일 리스트 추가했습니다.
FileMapper.xml -- 마케팅 리스트 매퍼 추가했습니다.
FileService.java -- 마케팅 리스트 서비스 추가했습니다.
sideBar.html -- 경로 설정 후 화면 연결했습니다.

[mapper 수정, 사이드바 경로 설정 및 화면 연결 rjy]

---

ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminWorkController.java
ks45team01/src/main/java/ks45team01/unity/dto/Work.java
ks45team01/src/main/java/ks45team01/unity/dto/WorkType.java
ks45team01/src/main/java/ks45team01/unity/mapper/WorkMapper.java
ks45team01/src/main/java/ks45team01/unity/service/WorkService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/WorkController.java
ks45team01/src/main/resources/mapper/WorkMapper.xml
ks45team01/src/main/resources/templates/main.html
ks45team01/src/main/resources/templates/messenger/messenger_chat_list.html
ks45team01/src/main/resources/templates/messenger/messenger_worker_list.html
ks45team01/src/main/resources/templates/settings/vacation_insert.html
ks45team01/src/main/resources/templates/settings/vacation_variety_insert.html
ks45team01/src/main/resources/templates/settings/vacation_variety_list.html
ks45team01/src/main/resources/templates/settings/vacation_variety_modify.html
ks45team01/src/main/resources/templates/settings/work_type_insert.html
ks45team01/src/main/resources/templates/settings/work_type_list.html
ks45team01/src/main/resources/templates/settings/work_type_modify.html
ks45team01/src/main/resources/templates/vacation/vacation_info_all_list.html
ks45team01/src/main/resources/templates/vacation/vacation_info_department_list.html
ks45team01/src/main/resources/templates/vacation/vacation_info_list.html
ks45team01/src/main/resources/templates/work/work_all_list.html
ks45team01/src/main/resources/templates/work/work_authority_Insert.html
ks45team01/src/main/resources/templates/work/work_authority_list.html
ks45team01/src/main/resources/templates/work/work_department_list.html
ks45team01/src/main/resources/templates/work/work_list.html

WorkMapper.java
WorkMapeer.xml
WorkService.java
Work.java
[근태 조회를 위한 controller 수정]
AdminWorkController.java
[breadcrumbar 수정]
main.html
messenger_chat_list.html
messenger_worker_list.html
vacation_info_all_list.html
vacation_info_department_list.html
vacation_info_list.html
vacation_insert.html
vacation_variety_insert.html
vacation_variety_list.html
vacation_variety_modify.html
work_all_list.html
vacation_variety_modify.html
work_all_list.html
work_authority_Insert.html
work_authority_list.html
work_department_list.html
work_list.html
work_type_insert.html
work_type_list.html
work_type_modify.html

[근태 조회를 위한 mapper, dto, service생성]

---

ks45team01/src/main/java/ks45team01/unity/dto/MemberLevel.java
ks45team01/src/main/java/ks45team01/unity/mapper/MemberLevelMapper.java
ks45team01/src/main/java/ks45team01/unity/service/MemberLevelService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/MemberController.java
ks45team01/src/main/resources/mapper/MemberLevelMapper.xml
ks45team01/src/main/resources/templates/member/member_level_list.html
ks45team01/src/main/resources/templates/project/project_home.html

추가
ks45team01/src/main/java/ks45team01/unity/dto/MemberLevel.java ks45team01/src/main/java/ks45team01/unity/mapper/MemberLevelMapper.java ks45team01/src/main/resources/mapper/MemberLevelMapper.xml ks45team01/src/main/java/ks45team01/unity/service/MemberLevelService.java 수정
ks45team01/src/main/resources/templates/member/member_level_list.html ks45team01/src/main/java/ks45team01/unity/worker/controller/MemberController.java ks45team01/src/main/resources/templates/project/project_home.html

[멤버레벨권한 맵퍼및 서비스 컨트롤러 수정,프로젝트 홈 화면 수정 jhw]

---

ks45team01/src/main/java/ks45team01/unity/dto/MemberLevel.java
ks45team01/src/main/resources/mapper/MemberLevelMapper.xml
ks45team01/src/main/resources/templates/member/member_level_list.html
ks45team01/src/main/resources/templates/member/member_level_modify.html

수정
ks45team01/src/main/resources/templates/member/member_level_list.html ks45team01/src/main/resources/templates/member/member_level_modify.html ks45team01/src/main/java/ks45team01/unity/dto/MemberLevel.java ks45team01/src/main/resources/mapper/MemberLevelMapper.xml

[멤버레벨 dto설정 및 수정]

---

ks45team01/src/main/java/ks45team01/unity/mapper/FileMapper.java
ks45team01/src/main/java/ks45team01/unity/service/FileService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/FileController.java
ks45team01/src/main/resources/mapper/FileMapper.xml

수정
FileController.java -- 페이지 마다 카테고리 코드를 받아올 수 있도록 조건문 사용해서 수정했습니다. 
FileMapper.java -- 모든 카테고리를 보여주기 위해 목록을 만들었습니다.
FileMapper.xml -- 카테고리 목록에 대한 mapper 수정했습니다.

[카테고리 별 페이지 추가 및 컨트롤러 수정 rjy]

---

ks45team01/src/main/resources/templates/community/boardInsert.html
ks45team01/src/main/resources/templates/community/boardList.html
ks45team01/src/main/resources/templates/community/boardModify.html
ks45team01/src/main/resources/templates/community/noticeInsert.html
ks45team01/src/main/resources/templates/community/noticeList.html

화면수정
ks45team01/src/main/resources/templates/community/boardInsert.html ks45team01/src/main/resources/templates/community/boardList.html ks45team01/src/main/resources/templates/community/boardModify.html ks45team01/src/main/resources/templates/community/noticeInsert.html ks45team01/src/main/resources/templates/community/noticeList.html

[커뮤니티 게시판, 공지사항 화면 수정 jsh]

---

ks45team01/src/main/java/ks45team01/unity/mapper/ReservationMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ReservationService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ReservationController.java
ks45team01/src/main/resources/mapper/ReservationMapper.xml
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_insert.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_list.html

[예약 화면 수정 jmj]

---

ks45team01/src/main/java/ks45team01/unity/worker/controller/FileBoardController.java
ks45team01/src/main/resources/templates/fileBoard/addBoardFile.html
ks45team01/src/main/resources/templates/fileBoard/fileBoardUpdate.html
ks45team01/src/main/resources/templates/fileBoard/fileBoardView.html
ks45team01/src/main/resources/templates/fileBoard/hrList.html

수정
addBoardFile.html -- 파일게시글 등록 수정하였습니다.
FileBoardController.java -- 파일게시글 컨트롤러 등록, 수정, 상세보기 매핑 다시 설정했습니다.
fileBoardUpdate.html -- 파일게시글 업데이트 수정하였습니다.
fileBoardView.html -- 파일게시글 상세보기 오류 및 수정하였습니다.
hrList.html -- 인사파일게시글 리스트 경로 수정하였습니다.

[파일게시글 등록, 업데이트, 상세보기 수정 rjy]

---

ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminWorkController.java
ks45team01/src/main/java/ks45team01/unity/dto/VacationCategory.java
ks45team01/src/main/java/ks45team01/unity/dto/VacationSort.java
ks45team01/src/main/java/ks45team01/unity/dto/VacationStandard.java
ks45team01/src/main/java/ks45team01/unity/dto/VacationType.java
ks45team01/src/main/java/ks45team01/unity/mapper/VacationMapper.java
ks45team01/src/main/java/ks45team01/unity/service/VacationService.java
ks45team01/src/main/resources/mapper/VacationMapper.xml
ks45team01/src/main/resources/mapper/WorkTypeMapper.xml
ks45team01/src/main/resources/templates/settings/vacation_variety_list.html
ks45team01/src/main/resources/templates/settings/work_type_list.html

수정
AdminWorkController.java
vacation_variety_list.html
work_type_list.html
WorkTypeMapper.xml
추가
<dto>
VacationCategory.java
VacationSort.java
VacationStandard.java
VacationType.java
<mapper>
VacationMapper.java
VacationMapper.xml
<service>
VacationService.java

[휴가설정 조회 수정 kjy]

---

ks45team01/src/main/java/ks45team01/unity/dto/MemberList.java
ks45team01/src/main/java/ks45team01/unity/dto/Reservation.java
ks45team01/src/main/java/ks45team01/unity/mapper/MemberListMapper.java
ks45team01/src/main/java/ks45team01/unity/service/MemberListService.java
ks45team01/src/main/resources/mapper/MemberListMapper.xml
ks45team01/src/main/resources/templates/project/project.html
ks45team01/src/main/resources/templates/project/project_member_insert.html
ks45team01/src/main/resources/templates/project/project_member_modify.html

이름변경
ks45team01/src/main/java/ks45team01/unity/dto/listMember.java ks45team01/src/main/java/ks45team01/unity/dto/MemberList.java 추가
ks45team01/src/main/java/ks45team01/unity/mapper/MemberListMapper.java ks45team01/src/main/resources/mapper/MemberListMapper.xml ks45team01/src/main/java/ks45team01/unity/service/MemberListService.java 수정
ks45team01/src/main/resources/templates/project/project.html ks45team01/src/main/resources/templates/project/project_member_insert.html ks45team01/src/main/resources/templates/project/project_member_modify.html ks45team01/src/main/java/ks45team01/unity/dto/Reservation.java

[리스트멤버이름변경 및 맵퍼 서비스 추가 프로젝트 화면 수정 jhw]

---

ks45team01/src/main/java/ks45team01/unity/dto/MemberList.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/MemberController.java
ks45team01/src/main/resources/templates/fragments/sideBar.html
ks45team01/src/main/resources/templates/member/member.html
ks45team01/src/main/resources/templates/member/member_department_manige.html
ks45team01/src/main/resources/templates/member/member_position_manige.html
ks45team01/src/main/resources/templates/project/project_insert.html
ks45team01/src/main/resources/templates/project/project_modify.html

추가
ks45team01/src/main/resources/templates/member/member_department_manige.html ks45team01/src/main/resources/templates/member/member_position_manige.html 수정
ks45team01/src/main/resources/templates/member/member.html ks45team01/src/main/java/ks45team01/unity/worker/controller/MemberController.java ks45team01/src/main/java/ks45team01/unity/dto/MemberList.java ks45team01/src/main/resources/templates/project/project_insert.html ks45team01/src/main/resources/templates/project/project_modify.html ks45team01/src/main/resources/templates/fragments/sideBar.html

[직급사원관리 부서사원관리추가 및 컨트롤러 추가 프로젝트및 사이드바 수정 jhw]

---

ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminReservationController.java
ks45team01/src/main/java/ks45team01/unity/mapper/ReservationMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ReservationService.java
ks45team01/src/main/resources/mapper/ReservationMapper.xml
ks45team01/src/main/resources/templates/reservation/meetingroom_list.html
ks45team01/src/main/resources/templates/reservation/meetingroom_modify.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_insert.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_list.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_modify.html

controller/AdminReservationController.java
reservation/meetingroom_list.html
reservation/meetingroom_modify.html
reservation/meetingroom_reservation_modify.html

[예약 회의실 관리 페이지 수정삭제처리 jmj]

---

ks45team01/src/main/java/ks45team01/unity/dto/CalenderCategory.java
ks45team01/src/main/java/ks45team01/unity/dto/CalenderInput.java
ks45team01/src/main/java/ks45team01/unity/dto/CommunityBoard.java
ks45team01/src/main/java/ks45team01/unity/dto/CommunityNotice.java
ks45team01/src/main/java/ks45team01/unity/mapper/CalenderCategoryMapper.java
ks45team01/src/main/java/ks45team01/unity/mapper/CalenderInputMapper.java
ks45team01/src/main/java/ks45team01/unity/mapper/CommunityBoardMapper.java
ks45team01/src/main/java/ks45team01/unity/mapper/CommunityNoticeMapper.java

파일 추가
ks45team01/src/main/java/ks45team01/unity/dto/CalenderCategory.java ks45team01/src/main/java/ks45team01/unity/mapper/CalenderCategoryMapper.java ks45team01/src/main/java/ks45team01/unity/dto/CalenderInput.java ks45team01/src/main/java/ks45team01/unity/mapper/CalenderInputMapper.java ks45team01/src/main/java/ks45team01/unity/dto/CommunityBoard.java ks45team01/src/main/java/ks45team01/unity/mapper/CommunityBoardMapper.java ks45team01/src/main/java/ks45team01/unity/dto/CommunityNotice.java ks45team01/src/main/java/ks45team01/unity/mapper/CommunityNoticeMapper.java

[캘린더 ,커뮤니티 게시판, 공지사항 dto,Mapper 추가]

---

ks45team01/src/main/java/ks45team01/unity/dto/DepartmentManage.java
ks45team01/src/main/java/ks45team01/unity/dto/PositionManage.java
ks45team01/src/main/java/ks45team01/unity/mapper/DepartmentManageMapper.java
ks45team01/src/main/java/ks45team01/unity/mapper/PositionManageMapper.java
ks45team01/src/main/java/ks45team01/unity/service/DepartmentManageService.java
ks45team01/src/main/java/ks45team01/unity/service/PositionManageService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/MemberController.java
ks45team01/src/main/resources/mapper/DepartmentManageMapper.xml
ks45team01/src/main/resources/mapper/PositionManageMapper.xml
ks45team01/src/main/resources/templates/member/member_department_manige.html
ks45team01/src/main/resources/templates/member/member_position_manige.html

추가
ks45team01/src/main/java/ks45team01/unity/dto/DepartmentManage.java ks45team01/src/main/java/ks45team01/unity/mapper/DepartmentManageMapper.java ks45team01/src/main/resources/mapper/DepartmentManageMapper.xml ks45team01/src/main/java/ks45team01/unity/service/DepartmentManageService.java ks45team01/src/main/java/ks45team01/unity/dto/PositionManage.java ks45team01/src/main/java/ks45team01/unity/mapper/PositionManageMapper.java ks45team01/src/main/resources/mapper/PositionManageMapper.xml ks45team01/src/main/java/ks45team01/unity/service/PositionManageService.java 수정
ks45team01/src/main/resources/templates/member/member_department_manige.html ks45team01/src/main/resources/templates/member/member_position_manige.html ks45team01/src/main/java/ks45team01/unity/worker/controller/MemberControll …

[DepartmentManage PositionManage맵퍼 및 서비스 추가 및 화면 수정 jhw]

---

ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_insert.html

[예약 추가 페이지 시간 클릭버튼 수정 jmj]

---

ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminFileBoardCateController.java
ks45team01/src/main/java/ks45team01/unity/dto/FileBoard.java
ks45team01/src/main/java/ks45team01/unity/dto/FileBoardCate.java
ks45team01/src/main/java/ks45team01/unity/mapper/FileBoardMapper.java
ks45team01/src/main/java/ks45team01/unity/service/FileBoardService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/FileBoardController.java
ks45team01/src/main/resources/mapper/FileBoardMapper.xml
ks45team01/src/main/resources/templates/fileBoard/addBoardFile.html
ks45team01/src/main/resources/templates/fileBoard/fileBoardView.html
ks45team01/src/main/resources/templates/fileBoard/marketingList.html
ks45team01/src/main/resources/templates/fileBoardCate/addFileBoardCate.html
ks45team01/src/main/resources/templates/fileBoardCate/fileBoardCateList.html
ks45team01/src/main/resources/templates/fileBoardCate/fileBoardCateModify.html

수정
addBoardFile.html -- 카테고리 별 파일 등록 처리완료
FileBoardController.java
FileBoardMapper.java -- 전체 카테고리 및 파일 조회 처리완료
FileBoardMapper.xml -- 전체 카테고리 및 파일 조회 쿼리문 작성
FileBoardService.java -- 전체 카테고리 및 파일 조회 서비스 작성
fileBoardView.html
marketingList.html
추가
addFileBoardCate.html
AdminFileBoardCateController.java -- 파일 카테고리 컨트롤러 CRUD 작성
FileBoardCate.java -- 파일 카테고리 DTO작성
fileBoardCateList.html
fileBoardCateModify.html

[카테고리 별 파일게시글 등록처리 및 카테고리 CRUD완료 rjy]

---

ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminMajorCateGoryController.java
ks45team01/src/main/java/ks45team01/unity/dto/MajorCateGory.java
ks45team01/src/main/java/ks45team01/unity/mapper/ApprovalMapper.java
ks45team01/src/main/java/ks45team01/unity/mapper/MajorCategoryMapper.java
ks45team01/src/main/java/ks45team01/unity/service/MajorCategoryService.java
ks45team01/src/main/resources/mapper/MajorCategoryMapper.xml
ks45team01/src/main/resources/templates/approval/draftInsert.html
ks45team01/src/main/resources/templates/fragments/sideBar.html
ks45team01/src/main/resources/templates/manageCate/majorCateList.html

추가
AdminMajorCateGoryController.java -- 대분류 카테고리 조회 컨트롤러 작성
ApprovalMapper.java -- 결재 매퍼만 생성
MajorCateGory.java -- 대분류 카테고리 DTO 작성
MajorCategoryMapper.java -- 대분류 카테고리 조회 메서드 선언
MajorCategoryMapper.xml -- 대분류 카테고리 조회 매퍼 작성
MajorCategoryService.java -- 대분류 카테고리 조회 서비스 작성
majorCateList.html -- view 작성
수정
draftInsert.html
sideBar.html -- 메뉴 링크 수정했습니다.

[대분류 카테고리 조회 및 사이드바 수정 rjy]

---

ks45team01/src/main/java/ks45team01/unity/dto/MemberDepartmentList.java
ks45team01/src/main/java/ks45team01/unity/dto/MemberPositionList.java
ks45team01/src/main/java/ks45team01/unity/dto/ProjectBoard.java
ks45team01/src/main/java/ks45team01/unity/dto/ProjectUnit.java
ks45team01/src/main/java/ks45team01/unity/mapper/MemberPositionListMapper.java
ks45team01/src/main/java/ks45team01/unity/mapper/ProjectBoardMapper.java
ks45team01/src/main/java/ks45team01/unity/mapper/ProjectUnitMapper.java
ks45team01/src/main/java/ks45team01/unity/service/MemberPositionListService.java
ks45team01/src/main/java/ks45team01/unity/service/ProjectBoardService.java
ks45team01/src/main/java/ks45team01/unity/service/ProjectUnitService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/MemberController.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java
ks45team01/src/main/resources/mapper/MemberDepartmentListMapper.xml
ks45team01/src/main/resources/mapper/MemberPositionListMapper.xml
ks45team01/src/main/resources/mapper/ProjectBoardMapper.xml
ks45team01/src/main/resources/mapper/ProjectUnitMapper.xml
ks45team01/src/main/resources/templates/member/member_department_list.html
ks45team01/src/main/resources/templates/member/member_position_list.html
ks45team01/src/main/resources/templates/project/project_home.html
ks45team01/src/main/resources/templates/project/project_insert.html

추가
ks45team01/src/main/java/ks45team01/unity/dto/MemberPositionList.java ks45team01/src/main/java/ks45team01/unity/mapper/MemberPositionListMapper.java ks45team01/src/main/resources/mapper/MemberPositionListMapper.xml ks45team01/src/main/java/ks45team01/unity/service/MemberPositionListService.java ks45team01/src/main/java/ks45team01/unity/dto/ProjectBoard.java ks45team01/src/main/java/ks45team01/unity/mapper/ProjectBoardMapper.java ks45team01/src/main/resources/mapper/ProjectBoardMapper.xml ks45team01/src/main/java/ks45team01/unity/service/ProjectBoardService.java ks45team01/src/main/java/ks45team01/unity/dto/ProjectUnit.java ks45team01/src/main/java/ks45team01/unity/mapper/ProjectUnitMapper.java ks45team01/src/main/resources/mapper/ProjectUnitMapper.xml …

[멤버 부서및 직급리스트 화면수정 및 맵퍼추가 jhw]

---

ks45team01/src/main/resources/templates/calender/calenderPersonalList.html
ks45team01/src/main/resources/templates/calender/scheduelList.html
ks45team01/src/main/resources/templates/todolist/todoList.html

ks45team01/src/main/resources/templates/calender/calenderPersonalList.html ks45team01/src/main/resources/templates/calender/scheduelList.html ks45team01/src/main/resources/templates/todolist/todoList.html

[todolist 화면수정 및 캘린더 경로 수정 jsh]

---

ks45team01/src/main/java/ks45team01/unity/dto/ProjectRequest.java
ks45team01/src/main/java/ks45team01/unity/dto/ProjectUnitMember.java
ks45team01/src/main/java/ks45team01/unity/mapper/ProjectRequestMapper.java
ks45team01/src/main/java/ks45team01/unity/mapper/ProjectUnitMemberMapper.java
ks45team01/src/main/java/ks45team01/unity/service/MemberListService.java
ks45team01/src/main/java/ks45team01/unity/service/ProjectRequestService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java
ks45team01/src/main/resources/mapper/ProjectRequestMapper.xml
ks45team01/src/main/resources/mapper/ProjectUnitMemberMapper.xml
ks45team01/src/main/resources/static/assets/js/app.js
ks45team01/src/main/resources/templates/project/project.html
ks45team01/src/main/resources/templates/project/project_home.html
ks45team01/src/main/resources/templates/project/project_task.html

추가
ks45team01/src/main/java/ks45team01/unity/dto/ProjectRequest.java ks45team01/src/main/java/ks45team01/unity/mapper/ProjectRequestMapper.java ks45team01/src/main/resources/mapper/ProjectRequestMapper.xml ks45team01/src/main/java/ks45team01/unity/service/ProjectRequestService.java ks45team01/src/main/java/ks45team01/unity/dto/ProjectUnitMember.java ks45team01/src/main/java/ks45team01/unity/mapper/ProjectUnitMemberMapper.java ks45team01/src/main/resources/mapper/ProjectUnitMemberMapper.xml
수정
ks45team01/src/main/java/ks45team01/unity/service/MemberListService.java ks45team01/src/main/resources/templates/project/project.html ks45team01/src/main/resources/templates/project/project_home.html ks45team01/src/main/resources/templates/project/project_task.html …

[프로젝트리퀘스트 맵퍼 추가 화면 수정]

---

ks45team01/src/main/java/ks45team01/unity/mapper/TodoMapper.java
ks45team01/src/main/java/ks45team01/unity/service/TodoService.java
ks45team01/src/main/resources/templates/todolist/todoList.html

ks45team01/src/main/resources/templates/todolist/todoList.html ks45team01/src/main/java/ks45team01/unity/service/TodoService.java ks45team01/src/main/java/ks45team01/unity/mapper/TodoMapper.java

[todolist  화면 ,service 수정 jsh]

---

ks45team01/src/main/java/ks45team01/unity/dto/MemberList.java
ks45team01/src/main/java/ks45team01/unity/mapper/MemberListMapper.java
ks45team01/src/main/java/ks45team01/unity/service/MemberListService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/MemberController.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java
ks45team01/src/main/resources/mapper/MemberListMapper.xml
ks45team01/src/main/resources/templates/member/member.html

수정
ks45team01/src/main/resources/templates/member/member.html ks45team01/src/main/java/ks45team01/unity/worker/controller/MemberController.java ks45team01/src/main/java/ks45team01/unity/dto/MemberList.java ks45team01/src/main/java/ks45team01/unity/mapper/MemberListMapper.java ks45team01/src/main/resources/mapper/MemberListMapper.xml ks45team01/src/main/java/ks45team01/unity/service/MemberListService.java ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java

[사원관리 검색 및 페이징 수정 jhw]

---

ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_insert.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_list.html

[예약 추가 예약 목록 jmj]

---

ks45team01/src/main/java/ks45team01/unity/mapper/MemberModifyMapper.java
ks45team01/src/main/java/ks45team01/unity/service/MemberModifyService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/MemberController.java
ks45team01/src/main/resources/mapper/MemberModifyMapper.xml
ks45team01/src/main/resources/templates/member/member_modify.html

추가
ks45team01/src/main/java/ks45team01/unity/mapper/MemberModifyMapper.java ks45team01/src/main/resources/mapper/MemberModifyMapper.xml ks45team01/src/main/java/ks45team01/unity/service/MemberModifyService.java 수정
ks45team01/src/main/resources/templates/member/member_modify.html ks45team01/src/main/java/ks45team01/unity/worker/controller/MemberController.java

[멤버 수정 맵퍼 및 서비스 추가 화면 수정 jhw]

---

ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminWorkController.java
ks45team01/src/main/java/ks45team01/unity/dto/VacationCategory.java
ks45team01/src/main/java/ks45team01/unity/dto/VacationSort.java
ks45team01/src/main/java/ks45team01/unity/mapper/VacationMapper.java
ks45team01/src/main/java/ks45team01/unity/service/VacationService.java
ks45team01/src/main/resources/mapper/VacationMapper.xml
ks45team01/src/main/resources/templates/settings/vacation_category_insert.html
ks45team01/src/main/resources/templates/settings/vacation_category_modify.html
ks45team01/src/main/resources/templates/settings/vacation_sort_insert.html
ks45team01/src/main/resources/templates/settings/vacation_sort_modify.html
ks45team01/src/main/resources/templates/settings/vacation_type_insert.html
ks45team01/src/main/resources/templates/settings/vacation_type_modify.html
ks45team01/src/main/resources/templates/settings/vacation_variety_list.html

수정파일
AdminWorkController.java
VacationCategory.java
VacationMapper.xml
VacationService.java
VacationSort.java
생성파일
vacation_category_insert.html
vacation_category_modify.html
vacation_sort_insert.html
vacation_sort_modify.html
vacation_type_insert.html
vacation_type_modify.html
vacation_variety_insert.html
vacation_variety_list.html
vacation_variety_modify.html

[휴가 설정 수정 및 입력 파일 생성,수정 kjy]

---

ks45team01/src/main/java/ks45team01/unity/dto/FileBoard.java
ks45team01/src/main/java/ks45team01/unity/dto/FileDto.java
ks45team01/src/main/java/ks45team01/unity/mapper/FileBoardMapper.java
ks45team01/src/main/java/ks45team01/unity/mapper/FileMapper.java
ks45team01/src/main/java/ks45team01/unity/service/FileBoardService.java
ks45team01/src/main/java/ks45team01/unity/util/FileUtil.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/FileBoardController.java
ks45team01/src/main/resources/application.properties
ks45team01/src/main/resources/mapper/FileBoardMapper.xml
ks45team01/src/main/resources/mapper/FileMapper.xml
ks45team01/src/main/resources/templates/fileBoard/addBoardFile.html
ks45team01/src/main/resources/templates/fileBoard/fileBoardList.html
ks45team01/src/main/resources/templates/fileBoard/fileBoardUpdate.html
ks45team01/src/main/resources/templates/fileBoard/fileBoardView.html
ks45team01/src/main/resources/templates/fileBoard/fileList.html
ks45team01/src/main/resources/templates/fileBoard/hrList.html
ks45team01/src/main/resources/templates/fileBoard/managementSupportList.html
ks45team01/src/main/resources/templates/fileBoard/marketingList.html
ks45team01/src/main/resources/templates/fileBoard/planningDept.html
ks45team01/src/main/resources/templates/fileBoardCate/addFileBoardCate.html

추가
fileBoardList.html
FileDto.java -- 파일 관리 DTO 추가
FileMapper.java -- 파일 관리 매퍼 인터페이스 추가
FileMapper.xml -- 파일 관리 매퍼 추가
FileUtil.java -- 파일 util 추가
수정
addBoardFile.html -- 파일게시글 등록에 파일 첨부 추가
application.properties -- properties에 파일 용량 설정 추가
FileBoard.java -- 파일게시글 등록 수정
FileBoardController.java -- 첨부파일 업로드 컨트롤러 수정
FileBoardMapper.java -- 파일 매퍼 인터페이스 수정
FileBoardMapper.xml -- 파일 매퍼 쿼리문 수정
FileBoardService.java -- 첨부파일 업로드 서비스 수정
fileBoardView.html

[파일 첨부 추가 및 보안 rjy]

---

ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminMemberController.java
ks45team01/src/main/resources/templates/fragments/sideBar.html
ks45team01/src/main/resources/templates/member/memberAdmin.html
ks45team01/src/main/resources/templates/member/member_admin_modify.html

추가
ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminMemberController.java ks45team01/src/main/resources/templates/member/member_admin_modify.html 수정
ks45team01/src/main/resources/templates/member/member_modify.html ks45team01/src/main/resources/templates/member/memberAdmin.html ks45team01/src/main/resources/templates/fragments/sideBar.html

[어드민맴버 컨트롤러 생성 및 어드민 수정화면 추가 사이드바 수정 jwh]

---

ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_insert.html

[예약 추가 시간선택 변경 jmj]

---

ks45team01/src/main/java/ks45team01/unity/mapper/ReservationMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ReservationService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ReservationController.java
ks45team01/src/main/resources/mapper/ReservationMapper.xml
ks45team01/src/main/resources/templates/reservation/meetingroom_list.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_insert.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_list.html

reservation/meetingroom_list.html

[예약 추가 설정 jmj]

---

ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminMemberController.java
ks45team01/src/main/java/ks45team01/unity/mapper/MemberListMapper.java
ks45team01/src/main/java/ks45team01/unity/mapper/MemberModifyMapper.java
ks45team01/src/main/java/ks45team01/unity/service/MemberListService.java
ks45team01/src/main/java/ks45team01/unity/service/MemberModifyService.java
ks45team01/src/main/resources/mapper/MemberListMapper.xml
ks45team01/src/main/resources/mapper/MemberModifyMapper.xml
ks45team01/src/main/resources/templates/member/memberAdmin.html
ks45team01/src/main/resources/templates/member/member_admin_modify.html
ks45team01/src/main/resources/templates/member/member_department_manige.html
ks45team01/src/main/resources/templates/member/member_modify.html

수정
ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminMemberController.java ks45team01/src/main/resources/templates/member/member_admin_modify.html ks45team01/src/main/resources/templates/member/member_department_manige.html ks45team01/src/main/resources/templates/member/member_modify.html ks45team01/src/main/resources/templates/member/memberAdmin.html ks45team01/src/main/java/ks45team01/unity/mapper/MemberListMapper.java ks45team01/src/main/resources/mapper/MemberListMapper.xml ks45team01/src/main/java/ks45team01/unity/service/MemberListService.java ks45team01/src/main/java/ks45team01/unity/mapper/MemberModifyMapper.java ks45team01/src/main/resources/mapper/MemberModifyMapper.xml ks45team01/src/main/java/ks45team01/unity/service/MemberModifyService.java

[멤버 컨트롤러,어드민 멤버 컨트롤러 멤버수정 화면수정 jhw]

---

ks45team01/src/main/java/ks45team01/unity/dto/FileBoard.java
ks45team01/src/main/java/ks45team01/unity/service/FileBoardService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ApprovalController.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/FileBoardController.java
ks45team01/src/main/resources/mapper/FileBoardMapper.xml
ks45team01/src/main/resources/mapper/FileMapper.xml
ks45team01/src/main/resources/templates/approval/letterApprovalInsert.html
ks45team01/src/main/resources/templates/approval/odInsert.html
ks45team01/src/main/resources/templates/approval/proposalInsert.html
ks45team01/src/main/resources/templates/fileBoard/addBoardFile.html
ks45team01/src/main/resources/templates/fileBoard/fileList.html
ks45team01/src/main/resources/templates/fileBoard/hrList.html
ks45team01/src/main/resources/templates/fileBoard/managementSupportList.html
ks45team01/src/main/resources/templates/fileBoard/marketingList.html
ks45team01/src/main/resources/templates/fileBoard/planningDept.html
ks45team01/src/main/resources/templates/form/formList.html
ks45team01/src/main/resources/templates/form/formView.html

추가
letterApprovalInsert.html
odInsert.html
proposalInsert.html
추가
addBoardFile.html
ApprovalController.java
draftInsert.html
FileBoard.java
FileBoardController.java -- 카테고리 별 조회 및 등록 컨트롤러 추가 FileBoardMapper.xml -- 카테고리 별 조회 및 등록 매퍼 추가
FileBoardService.java
fileBoard/fileList.html
FileMapper.xml
formList.html
formView.html
hrList.html
managementSupportList.html
marketingList.html
planningDept.html

[전자결재 페이지 카테고리별 페이지 추가 및 파일 보안]

---

ks45team01/src/main/java/ks45team01/unity/worker/controller/FileBoardController.java
ks45team01/src/main/resources/mapper/FileBoardMapper.xml
ks45team01/src/main/resources/mapper/FileMapper.xml
ks45team01/src/main/resources/templates/fileBoard/hrList.html
ks45team01/src/main/resources/templates/fileBoard/managementSupportList.html
ks45team01/src/main/resources/templates/fileBoard/marketingList.html
ks45team01/src/main/resources/templates/fileBoard/planningDept.html

수정
FileBoardController.java -- 파일 카테고리별 조회 수정 화면에 servieList 추가
FileBoardMapper.xml -- 파일 카테고리별 조회 부서명, 직급명, 사원이름 출력되도록 join추가 및 수정 
hrList.html -- servieList 부서, 직급, 사원이름 출력
managementSupportList.html -- servieList 부서, 직급, 사원이름 출력 
marketingList.html -- servieList 부서, 직급, 사원이름 출력
planningDept.html -- servieList 부서, 직급, 사원이름 출력

[파일 카테고리별 게시글 작업 완료 rjy]

---

ks45team01/src/main/java/ks45team01/unity/dto/ProjectMember.java
ks45team01/src/main/java/ks45team01/unity/mapper/ProjectMemberInsertMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ProjectMemberInsertService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java
ks45team01/src/main/resources/mapper/ProjectMemberInsertMapper.xml
ks45team01/src/main/resources/templates/project/project.html
ks45team01/src/main/resources/templates/project/project_member_insert.html

수정
ks45team01/src/main/resources/templates/project/project.html ks45team01/src/main/resources/templates/project/project_member_insert.html ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java 추가
ks45team01/src/main/java/ks45team01/unity/dto/ProjectMember.java ks45team01/src/main/java/ks45team01/unity/mapper/ProjectMemberInsertMapper.java ks45team01/src/main/resources/mapper/ProjectMemberInsertMapper.xml ks45team01/src/main/java/ks45team01/unity/service/ProjectMemberInsertService.java

[프로젝트 화면 프로젝트인원배정 맵퍼 서비스 추가]

---

ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminVacationController.java
ks45team01/src/main/java/ks45team01/unity/dto/VacationInformation.java
ks45team01/src/main/java/ks45team01/unity/mapper/VacationMapper.java
ks45team01/src/main/java/ks45team01/unity/service/VacationService.java
ks45team01/src/main/resources/mapper/VacationMapper.xml
ks45team01/src/main/resources/templates/fragments/sideBar.html
ks45team01/src/main/resources/templates/settings/vacation_insert.html
ks45team01/src/main/resources/templates/settings/vacation_insert_all.html
ks45team01/src/main/resources/templates/settings/vacation_insert_other.html
ks45team01/src/main/resources/templates/vacation/vacation_info_all_list.html

수정
AdminVacationController.java
sideBar.html
vacation_info_all_list.html
vacation_insert.html
VacationInformation.java
VacationMapper.java
VacationMapper.xml
VacationService.java
추가
vacation_insert_all.html
vacation_insert_other.html

[휴가 부여 수정 및 추가 kjy]

---

ks45team01/src/main/java/ks45team01/unity/dto/Reservation.java
ks45team01/src/main/java/ks45team01/unity/mapper/ReservationMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ReservationService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ReservationController.java
ks45team01/src/main/resources/mapper/ReservationMapper.xml
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_insert.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_list.html

**reservation/meetingroom_reservation_insert.html**
dto/Reservation.java

[예약추가 수정 jmj]

---

ks45team01/src/main/java/ks45team01/unity/dto/LoginHistory.java
ks45team01/src/main/java/ks45team01/unity/mapper/LoginMapper.java
ks45team01/src/main/java/ks45team01/unity/service/LoginService.java
ks45team01/src/main/resources/templates/community/boardDetail.html
ks45team01/src/main/resources/templates/community/boardModify.html
ks45team01/src/main/resources/templates/community/noticeModify.html
ks45team01/src/main/resources/templates/login/loginHistory.html

ks45team01/src/main/resources/templates/community/boardModify.html ks45team01/src/main/resources/templates/login/loginHistory.html ks45team01/src/main/java/ks45team01/unity/dto/LoginHistory.java ks45team01/src/main/java/ks45team01/unity/mapper/LoginMapper.java ks45team01/src/main/java/ks45team01/unity/service/LoginService.java ks45team01/src/main/resources/templates/community/noticeModify.html

[커뮤니티 화면 수정 및 로그인 추가 jsh]

---

ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminVacationController.java
ks45team01/src/main/java/ks45team01/unity/mapper/VacationMapper.java
ks45team01/src/main/java/ks45team01/unity/service/VacationService.java
ks45team01/src/main/resources/mapper/VacationMapper.xml
ks45team01/src/main/resources/templates/settings/vacation_insert_all.html
ks45team01/src/main/resources/templates/settings/vacation_insert_other.html
ks45team01/src/main/resources/templates/vacation/vacation_info_all_list.html

수정
AdminVacationController.java
vacation_info_all_list.html
vacation_insert_all.html
vacation_insert_other.html
VacationMapper.java
VacationMapper.xml
VacationService.java

[기타 휴가 부여 수정 kjy]

---

ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_insert.html

[예약 시간등록 수정 jmj]

---

ks45team01/src/main/java/ks45team01/unity/dto/Approval.java
ks45team01/src/main/java/ks45team01/unity/dto/FormBoard.java
ks45team01/src/main/java/ks45team01/unity/mapper/ApprovalMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ApprovalService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ApprovalController.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/FileBoardController.java
ks45team01/src/main/resources/mapper/ApprovalMapper.xml
ks45team01/src/main/resources/mapper/FileMapper.xml
ks45team01/src/main/resources/mapper/FormBoardMapper.xml
ks45team01/src/main/resources/templates/approval/draftList.html
ks45team01/src/main/resources/templates/form/addForm.html
ks45team01/src/main/resources/templates/form/formList.html
ks45team01/src/main/resources/templates/form/formView.html

수정
addForm.html -- 등록화면 보안중
ApprovalController.java -- 기안목록 컨트롤러 작성 완료
ApprovalMapper.java -- 기안목록 매퍼인터페이스 작성 완료
draftList.html -- 기안목록 화면 출력 완료
FileBoardController.java --파일관련 컨트롤러 보안중
FileMapper.xml -- 파일 매퍼 IGNORE 추가
FormBoard.java
FormBoardMapper.xml
formList.html -- 검색부분 보완중
formView.html
추가
Approval.java -- Approval DTO작성 완료
ApprovalMapper.xml -- 기안목록 매퍼쿼리 작성 완료
ApprovalService.java -- 기안목록 서비스 작성 완료

[서식 검색 보안 및 기안목록 완료, Approval.DTO작성 rjy]

---

ks45team01/src/main/java/ks45team01/unity/dto/ProjectList.java
ks45team01/src/main/java/ks45team01/unity/mapper/MemberListMapper.java
ks45team01/src/main/java/ks45team01/unity/mapper/ProjectListMapper.java
ks45team01/src/main/java/ks45team01/unity/mapper/ProjectMemberInsertMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ProjectListService.java
ks45team01/src/main/java/ks45team01/unity/service/ProjectMemberInsertService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java
ks45team01/src/main/resources/mapper/ProjectListMapper.xml
ks45team01/src/main/resources/mapper/ProjectMemberInsertMapper.xml
ks45team01/src/main/resources/templates/project/project.html
ks45team01/src/main/resources/templates/project/project_member_insert.html

수정
ks45team01/src/main/java/ks45team01/unity/mapper/MemberListMapper.java ks45team01/src/main/resources/templates/project/project.html ks45team01/src/main/resources/templates/project/project_member_insert.html ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java ks45team01/src/main/java/ks45team01/unity/dto/ProjectList.java ks45team01/src/main/java/ks45team01/unity/mapper/ProjectListMapper.java ks45team01/src/main/resources/mapper/ProjectListMapper.xml ks45team01/src/main/java/ks45team01/unity/service/ProjectListService.java ks45team01/src/main/java/ks45team01/unity/mapper/ProjectMemberInsertMapper.java ks45team01/src/main/resources/mapper/ProjectMemberInsertMapper.xml ks45team01/src/main/java/ks45team01/unity/service/ProjectMemberInsertService.java

[멤버 리스트 수정 프로젝트멤버인서트 수정 jhw]

---

ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_insert.html

[한거없는듯 ㅋ jmj]

---

ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminVacationController.java
ks45team01/src/main/java/ks45team01/unity/dto/WorkUnusual.java
ks45team01/src/main/resources/mapper/VacationMapper.xml
ks45team01/src/main/resources/mapper/WorkMapper.xml
ks45team01/src/main/resources/templates/settings/vacation_insert_all.html
ks45team01/src/main/resources/templates/settings/vacation_standard_insert.html
ks45team01/src/main/resources/templates/settings/vacation_standard_modify.html
ks45team01/src/main/resources/templates/settings/vacation_variety_list.html
ks45team01/src/main/resources/templates/work/work_authority_list.html

ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminVacationController.java ks45team01/src/main/resources/templates/settings/vacation_insert_all.html ks45team01/src/main/resources/templates/settings/vacation_standard_insert.html ks45team01/src/main/resources/templates/settings/vacation_standard_modify.html ks45team01/src/main/resources/templates/settings/vacation_variety_list.html ks45team01/src/main/resources/mapper/VacationMapper.xml ks45team01/src/main/resources/templates/work/work_authority_list.html ks45team01/src/main/resources/mapper/WorkMapper.xml ks45team01/src/main/java/ks45team01/unity/dto/WorkUnusual.java

[vacation 수정 kjy]

---

ks45team01/src/main/java/ks45team01/unity/mapper/ProjectListMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ProjectMemberInsertService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java
ks45team01/src/main/resources/mapper/ProjectListMapper.xml
ks45team01/src/main/resources/templates/project/project_member_insert.html

수정
ks45team01/src/main/resources/templates/project/project_member_insert.html ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java ks45team01/src/main/java/ks45team01/unity/mapper/ProjectListMapper.java ks45team01/src/main/resources/mapper/ProjectListMapper.xml ks45team01/src/main/java/ks45team01/unity/service/ProjectMemberInsertService.java

[프로젝트 멤버인원수 업데이트문 추가 jhw]

---

ks45team01/src/main/java/ks45team01/unity/mapper/ProjectListMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ProjectMemberInsertService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java
ks45team01/src/main/resources/mapper/ProjectMemberInsertMapper.xml
ks45team01/src/main/resources/templates/project/project_member_insert.html

수정
ks45team01/src/main/resources/templates/project/project_member_insert.html ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java ks45team01/src/main/java/ks45team01/unity/mapper/ProjectListMapper.java ks45team01/src/main/resources/mapper/ProjectMemberInsertMapper.xml ks45team01/src/main/java/ks45team01/unity/service/ProjectMemberInsertService.java

[프로젝트 삭제 준비중 jhw]

---

ks45team01/src/main/java/ks45team01/unity/mapper/ProjectListMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ProjectBoardService.java
ks45team01/src/main/java/ks45team01/unity/service/ProjectRequestService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java
ks45team01/src/main/resources/mapper/ProjectBoardMapper.xml
ks45team01/src/main/resources/mapper/ProjectRequestMapper.xml
ks45team01/src/main/resources/templates/project/project_member_insert.html

수정
ks45team01/src/main/resources/templates/project/project_member_insert.html ks45team01/src/main/resources/mapper/ProjectBoardMapper.xml ks45team01/src/main/java/ks45team01/unity/service/ProjectBoardService.java ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java ks45team01/src/main/java/ks45team01/unity/mapper/ProjectListMapper.java ks45team01/src/main/resources/mapper/ProjectRequestMapper.xml ks45team01/src/main/java/ks45team01/unity/service/ProjectRequestService.java

[프로젝트 게시글넘버에 따른 리스트화 및 프로젝트 맴버 삭제 완료 jhw]

---

ks45team01/src/main/java/ks45team01/unity/mapper/ProjectListMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ProjectBoardService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java
ks45team01/src/main/resources/mapper/ProjectBoardMapper.xml
ks45team01/src/main/resources/templates/project/project_detail.html
ks45team01/src/main/resources/templates/project/project_home.html
ks45team01/src/main/resources/templates/project/project_home/project_board_insert.html
ks45team01/src/main/resources/templates/project/project_member_insert.html

수정
ks45team01/src/main/resources/templates/project/project_home/project_board_insert.html ks45team01/src/main/resources/templates/project/project_detail.html ks45team01/src/main/resources/templates/project/project_home.html ks45team01/src/main/resources/templates/project/project_member_insert.html ks45team01/src/main/resources/mapper/ProjectBoardMapper.xml ks45team01/src/main/java/ks45team01/unity/service/ProjectBoardService.java ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java ks45team01/src/main/java/ks45team01/unity/mapper/ProjectListMapper.java

[프로젝트 게시글 등록 완료 및 프로젝트 멤버 중복아이디 진행중 jhw]

---

ks45team01/src/main/java/ks45team01/unity/dto/Approval.java
ks45team01/src/main/java/ks45team01/unity/dto/ApprovalProcess.java
ks45team01/src/main/java/ks45team01/unity/mapper/ApprovalMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ApprovalService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ApprovalController.java
ks45team01/src/main/resources/mapper/ApprovalMapper.xml
ks45team01/src/main/resources/templates/approval/approvalList.html
ks45team01/src/main/resources/templates/approval/approvalView.html
ks45team01/src/main/resources/templates/approval/draftList.html

수정
Approval.java -- 기안문서DTO에 결재프로세스DTO 추가
ApprovalController.java -- 개별 기안문서 상세보기 작업완료, 결재함 작업중 
approvalList.html -- 기안 목록 작업완료
ApprovalMapper.java -- 기안목록, 개별 기안문서 상세보기 결재함 Mapper 완료 
ApprovalMapper.xml -- 기안목록, 개별 기안문서 상세보기 결재함 쿼리문 완료 및 결재프로세스 association 추가 완료
ApprovalService.java -- 기안목록, 개별 기안문서 상세보기 서비스 기능 완료 결재함 작업중 
draftList.html -- 기안목록 화면연결 완료
draftView.html -- 기안상세보기 화면연결 완료
추가
ApprovalProcess.java -- 기안프로세스DTO 작성완료
approvalView.html -- 결재반려 작업중

[개별 기안상세보기 및 결재 진행목록 조회 rjy]

---

ks45team01/src/main/java/ks45team01/unity/mapper/CommunityNoticeMapper.java
ks45team01/src/main/java/ks45team01/unity/service/CommunityNoticeService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/CommunityController.java
ks45team01/src/main/resources/mapper/CommunityNoticeMapper.xml
ks45team01/src/main/resources/templates/community/noticeDetail.html
ks45team01/src/main/resources/templates/community/noticeInsert.html
ks45team01/src/main/resources/templates/community/noticeList.html
ks45team01/src/main/resources/templates/community/noticeModify.html

ks45team01/src/main/java/ks45team01/unity/worker/controller/CommunityController.java ks45team01/src/main/java/ks45team01/unity/mapper/CommunityNoticeMapper.java ks45team01/src/main/resources/mapper/CommunityNoticeMapper.xml ks45team01/src/main/java/ks45team01/unity/service/CommunityNoticeService.java ks45team01/src/main/resources/templates/community/noticeDetail.html ks45team01/src/main/resources/templates/community/noticeInsert.html ks45team01/src/main/resources/templates/community/noticeList.html ks45team01/src/main/resources/templates/community/noticeModify.html

[커뮤니티 공지사항 상세, 수정화면 텍스트상자 수정 jsh]

---

ks45team01/src/main/java/ks45team01/unity/dto/Approval.java
ks45team01/src/main/java/ks45team01/unity/dto/ApprovalLine.java
ks45team01/src/main/java/ks45team01/unity/mapper/ApprovalMapper.java
ks45team01/src/main/java/ks45team01/unity/mapper/FormBoardMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ApprovalService.java
ks45team01/src/main/java/ks45team01/unity/service/FormBoardService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ApprovalController.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/FormController.java
ks45team01/src/main/resources/mapper/ApprovalMapper.xml
ks45team01/src/main/resources/mapper/FormBoardMapper.xml
ks45team01/src/main/resources/templates/approval/approvalDoneList.html
ks45team01/src/main/resources/templates/approval/approvalDoneView.html
ks45team01/src/main/resources/templates/approval/draftInsert.html
ks45team01/src/main/resources/templates/approval/letterApprovalInsert.html
ks45team01/src/main/resources/templates/approval/odInsert.html
ks45team01/src/main/resources/templates/approval/proposalInsert.html
ks45team01/src/main/resources/templates/approval/rejectList.html
ks45team01/src/main/resources/templates/approval/rejectView.html
ks45team01/src/main/resources/templates/form/formList.html

수정
Approval.java -- Approval DTO approvalProcess, approvalLine 1대1 관계매핑 해두었습니다.
ApprovalController.java -- 페이징처리 및 반려처리, 기안 작성부분 수정 및 추가 했습니다. 
approvalDoneList.html -- 화면 구현중입니다.
approvalDoneView.html -- 화면 구현중입니다.
ApprovalMapper.java -- 반려처리 및 기안 작성부분 수청 및 추가 하였습니다.
ApprovalMapper.xml -- approvalProcess, approvalLine 조인을 위해 association 추가 하였습니다.
ApprovalService.java -- 반려처리 및 기안 작성부분 기능 수정 및 추가 하였습니다. 
approvalView.html -- 화면 구현중입니다.
draftInsert.html -- 화면 구현중입니다.
FormBoardMapper.java -- formList에 페이징 추가하였습니다.
FormBoardMapper.xml -- 페이징을 위한 formList에 Limit 쿼리문 추가하였습니다. 
FormBoardService.java -- 페이징 서비스 추가하였습니다.
FormController.java -- 페이징 기능 완료하였습니다.
formList.html -- 화면 구현중입니다.
letterApprovalInsert.html -- 화면 구현중입니다.
odInsert.html -- 화면 구현중입니다.
proposalInsert.html -- 화면 구현중입니다. …

[결재 반려처리 보안 및 페이징, 기안 작성 완료 rjy]

---

ks45team01/src/main/java/ks45team01/unity/dto/Reservation.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ReservationController.java
ks45team01/src/main/resources/mapper/ReservationMapper.xml
ks45team01/src/main/resources/templates/fragments/sideBar.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_insert.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_mine.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_modify.html

reservation/meetingroom_reservation_mine.html
reservation/meetingroom_reservation_modify.html
dto/Reservation.java
fragments/sideBar.html

[예약 메뉴 위치변경과 예약 시간 disabled성공 메뉴에 내예약관리 추가 +페이지 생성 jmj]

---

ks45team01/src/main/java/ks45team01/unity/admin/controller/LoginController.java
ks45team01/src/main/java/ks45team01/unity/dto/LoginInfo.java
ks45team01/src/main/java/ks45team01/unity/service/LoginService.java
ks45team01/src/main/resources/mapper/LoginMapper.xml
ks45team01/src/main/resources/templates/fragments/navigation.html
ks45team01/src/main/resources/templates/login/login.html

ks45team01/src/main/resources/templates/login/login.html ks45team01/src/main/java/ks45team01/unity/admin/controller/LoginController.java ks45team01/src/main/java/ks45team01/unity/dto/LoginInfo.java ks45team01/src/main/resources/mapper/LoginMapper.xml ks45team01/src/main/java/ks45team01/unity/service/LoginService.java ks45team01/src/main/resources/templates/fragments/navigation.html

[로그인 및 로그아웃 처리 jsh]

---

ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminReservationController.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ReservationController.java
ks45team01/src/main/resources/templates/reservation/meetingroom_insert.html
ks45team01/src/main/resources/templates/reservation/meetingroom_list.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_insert.html

controller/AdminReservationController.java
reservation/meetingroom_insert.html
reservation/meetingroom_list.html

[예약 회의실 등록 페이지 폼 수정 jmj]

---

ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminFileBoardCateController.java
ks45team01/src/main/java/ks45team01/unity/mapper/ApprovalMapper.java
ks45team01/src/main/java/ks45team01/unity/mapper/FileMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ApprovalService.java
ks45team01/src/main/java/ks45team01/unity/service/FileBoardService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ApprovalController.java
ks45team01/src/main/resources/mapper/ApprovalMapper.xml
ks45team01/src/main/resources/mapper/FileBoardMapper.xml
ks45team01/src/main/resources/templates/approval/approvalView.html
ks45team01/src/main/resources/templates/approval/draftInsert.html
ks45team01/src/main/resources/templates/approval/rejectView.html
ks45team01/src/main/resources/templates/fileBoardCate/fileBoardCateList.html
ks45team01/src/main/resources/templates/form/formList.html
ks45team01/src/main/resources/templates/fragments/footerScript.html

수정
AdminFileBoardCateController.java -- 파일 카테고리 수정 ajax작업중 
ApprovalController.java -- 결재처리 및 반려처리 완료
ApprovalMapper.java -- 결재처리 및 반려처리 매퍼추가
ApprovalMapper.xml -- 결재처리 및 반려처리 쿼리문 추가
ApprovalService.java -- 결재처리 및 반려처리 기능완료
approvalView.html -- 화면 연결 완료
draftInsert.html -- 기안 등록 화면 구현중
fileBoardCateList.html -- 카테고리 ajax 작업중
FileBoardMapper.xml -- 카테고리 ajax 쿼리 추가
FileBoardService.java -- 카테고리 ajax 기능 추가
FileMapper.java
footerScript.html -- 카테고리 ajax script문 추가 했습니다. 구현중 
formList.html -- 화면 구성 작업중
rejectView.html -- 반려 화면 작업중

[footerScript ajax 추가 및 결재처리, 반려처리완료 rjy]

---

ks45team01/src/main/java/ks45team01/unity/dto/ProjectBoard.java
ks45team01/src/main/java/ks45team01/unity/dto/ProjectComment.java
ks45team01/src/main/java/ks45team01/unity/dto/ProjectListPost.java
ks45team01/src/main/java/ks45team01/unity/dto/ProjectRequest.java
ks45team01/src/main/java/ks45team01/unity/mapper/ProjectListMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ProjectBoardService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java
ks45team01/src/main/resources/mapper/ProjectBoardMapper.xml
ks45team01/src/main/resources/templates/project/project_home.html

수정
ks45team01/src/main/resources/templates/project/project_home.html ks45team01/src/main/java/ks45team01/unity/dto/ProjectBoard.java ks45team01/src/main/resources/mapper/ProjectBoardMapper.xml ks45team01/src/main/java/ks45team01/unity/service/ProjectBoardService.java ks45team01/src/main/java/ks45team01/unity/dto/ProjectComment.java ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java ks45team01/src/main/java/ks45team01/unity/mapper/ProjectListMapper.java ks45team01/src/main/java/ks45team01/unity/dto/ProjectListPost.java ks45team01/src/main/java/ks45team01/unity/dto/ProjectRequest.java

[댓글 인서트 완료 및 프로젝트 화면리스트 완료 jhw]

---

ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminReservationController.java
ks45team01/src/main/java/ks45team01/unity/mapper/ReservationMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ReservationService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ReservationController.java
ks45team01/src/main/resources/mapper/ReservationMapper.xml
ks45team01/src/main/resources/templates/fragments/sideBar.html
ks45team01/src/main/resources/templates/reservation/meetingroom_insert.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_insert.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_list.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_mine.html

controller/AdminReservationController.java
reservation/meetingroom_insert.html
reservation/meetingroom_reservation_mine.html
templates/fragments/sideBar.html

[사이드바 경로 수정 예약 내 예약보기 수정 jmj]

---

ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminFileBoardCateController.java
ks45team01/src/main/java/ks45team01/unity/dto/FileBoardCate.java
ks45team01/src/main/java/ks45team01/unity/mapper/ApprovalMapper.java
ks45team01/src/main/java/ks45team01/unity/mapper/FileBoardMapper.java
ks45team01/src/main/java/ks45team01/unity/mapper/FileMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ApprovalService.java
ks45team01/src/main/java/ks45team01/unity/service/FileBoardService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ApprovalController.java
ks45team01/src/main/resources/mapper/ApprovalMapper.xml
ks45team01/src/main/resources/mapper/FileBoardMapper.xml
ks45team01/src/main/resources/templates/approval/draftInsert.html
ks45team01/src/main/resources/templates/approval/draftView.html
ks45team01/src/main/resources/templates/approval/letterApprovalInsert.html
ks45team01/src/main/resources/templates/approval/odInsert.html
ks45team01/src/main/resources/templates/approval/proposalInsert.html
ks45team01/src/main/resources/templates/fileBoard/addBoardFile.html
ks45team01/src/main/resources/templates/fileBoardCate/addFileBoardCate.html
ks45team01/src/main/resources/templates/fileBoardCate/fileBoardCateList.html
ks45team01/src/main/resources/templates/form/addForm.html
ks45team01/src/main/resources/templates/form/formList.html
ks45team01/src/main/resources/templates/fragments/footerScript.html

수정
addBoardFile.html -- 파일 등록자 로그인 세션 추가
addFileBoardCate.html -- 파일카테고리 등록자 로그인 세션 추가
addForm.html -- 서식 등록자 로그인 세션추가
AdminFileBoardCateController.java -- 파일 카테고리 로그인 세션 및 수정 ajax 완료 
ApprovalController.java
ApprovalMapper.java
ApprovalMapper.xml
ApprovalService.java
draftInsert.html -- 등록자 로그인 세션 추가
draftView.html -- 로그인 세션 추가
FileBoardCate.java -- DTO 수정
fileBoardCateList.html -- 카테고리 리스트 화면 수정
FileBoardMapper.java --  ajax 전용 매퍼 추가
FileBoardMapper.xml -- ajax 전용 쿼리문 추가
FileBoardService.java -- ajax 서비스 추가
FileMapper.java
footerScript.html 개인 ajax스크립트 작성 삭제
formList.html -- 로그인 세션 추가
letterApprovalInsert.html -- 등록자 로그인 세션 추가
odInsert.html -- 등록자 로그인 세션 추가
proposalInsert.html -- 등록자 로그인 세션 추가

[세션 연결 및 파일카테고리 수정 ajax 완료 rjy]

---

ks45team01/src/main/java/ks45team01/unity/mapper/ProjectListMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ProjectBoardService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java
ks45team01/src/main/resources/mapper/ProjectBoardMapper.xml
ks45team01/src/main/resources/templates/project/project_board_modify.html
ks45team01/src/main/resources/templates/project/project_home.html
ks45team01/src/main/resources/templates/project/project_home/project_task_insert.html

수정
ks45team01/src/main/resources/templates/project/project_board_modify.html ks45team01/src/main/resources/templates/project/project_home.html ks45team01/src/main/resources/templates/project/project_home/project_task_insert.html ks45team01/src/main/resources/mapper/ProjectBoardMapper.xml ks45team01/src/main/java/ks45team01/unity/service/ProjectBoardService.java ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java ks45team01/src/main/java/ks45team01/unity/mapper/ProjectListMapper.java

[프로젝트 게시글 수정 준비중 jhw]

---

ks45team01/src/main/java/ks45team01/unity/dto/ProjectBoard.java
ks45team01/src/main/java/ks45team01/unity/mapper/ProjectListMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ProjectBoardService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java
ks45team01/src/main/resources/mapper/ProjectBoardMapper.xml
ks45team01/src/main/resources/templates/project/project_board_modify.html
ks45team01/src/main/resources/templates/project/project_home.html

수정
ks45team01/src/main/resources/templates/project/project_board_modify.html ks45team01/src/main/resources/templates/project/project_home.html ks45team01/src/main/java/ks45team01/unity/dto/ProjectBoard.java ks45team01/src/main/resources/mapper/ProjectBoardMapper.xml ks45team01/src/main/java/ks45team01/unity/service/ProjectBoardService.java ks45team01/src/main/java/ks45team01/unity/worker/controller/ProjectController.java ks45team01/src/main/java/ks45team01/unity/mapper/ProjectListMapper.java

[프로젝트 게시글 수정 ver2 jhw]

---

ks45team01/src/main/java/ks45team01/unity/mapper/ReservationMapper.java
ks45team01/src/main/java/ks45team01/unity/service/ReservationService.java
ks45team01/src/main/java/ks45team01/unity/worker/controller/ReservationController.java
ks45team01/src/main/resources/mapper/ReservationMapper.xml
ks45team01/src/main/resources/templates/fragments/sideBar.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_insert.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_list.html

worker/controller/ReservationController.java
unity/service/ReservationService.java
templates/fragments/sideBar.html

[예약화면 예약목록화면 분리 jmj]

---

ks45team01/src/main/resources/templates/community/noticeDetail.html
ks45team01/src/main/resources/templates/fragments/top.html
ks45team01/src/main/resources/templates/login/loginInsert.html

ks45team01/src/main/resources/templates/login/loginInsert.html ks45team01/src/main/resources/templates/community/noticeDetail.html ks45team01/src/main/resources/templates/fragments/top.html

[로고 클릭시 메인화면  및 공지사항 텍스트 수정 jsh]

---

ks45team01/src/main/java/ks45team01/unity/worker/controller/ApprovalController.java
ks45team01/src/main/resources/mapper/ApprovalMapper.xml
ks45team01/src/main/resources/templates/fragments/sideBar.html

수정
ApprovalController.java
ApprovalMapper.xml -- 쿼리문 종결표시 추가
sideBar.html -- 파일 카테고리 메뉴 및 통합파일 메뉴 추가

[sideBar 파일 카테고리메뉴 추가]

---

ks45team01/src/main/resources/templates/project/project_member_insert.html

수정
ks45team01/src/main/resources/templates/project/project_member_insert.html

[멤버 인서트 화면 수정]

---

ks45team01/src/main/resources/mapper/FileBoardMapper.xml

수정
FileBoardMapper.xml -- 파일 카테고리 코드, 이름 조회에서 ORDER BY 추가하였습니다.

[파일 카테고리 코드, 이름 조회 정렬추가 rjy]

---

ks45team01/src/main/resources/templates/reservation/meetingroom_modify.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_insert.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_modify.html

reservation/meetingroom_modify.html
reservation/meetingroom_reservation_modify.html

[예약 추가 수정페이지 jmj]

---

ks45team01/src/main/resources/templates/project/project_member_insert.html

수정
ks45team01/src/main/resources/templates/project/project_member_insert.html

[test jhw]

---

ks45team01/src/main/resources/application.properties
ks45team01/src/main/resources/logback-spring.xml

logback-spring.xml 설정
/home/springboot/teamproject/logs
하위에 sql 로그 와 시스템 로그 분리

[loging file config setting - jmj]

---

ks45team01/src/main/java/ks45team01/unity/admin/controller/AdminReservationController.java

controller/AdminReservationController.java

[회의실 추가페이지 오류 수정 jmj]

---

ks45team01/src/main/java/ks45team01/unity/worker/controller/ReservationController.java
ks45team01/src/main/resources/templates/fragments/sideBar.html
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_all_list.html

templates/reservation/meetingroom_reservation_all_list.html worker/controller/ReservationController.java
templates/fragments/sideBar.html

[예약확인목록 페이지 생성 jmj]

---

ks45team01/src/main/java/ks45team01/unity/worker/controller/ReservationController.java
ks45team01/src/main/resources/templates/reservation/meetingroom_reservation_all_list.html

reservation/meetingroom_reservation_all_list.html

[전체예약확인 화면 수정 jmj]

---

ks45team01/src/main/resources/templates/login/login.html

ks45team01/src/main/resources/templates/login/login.html

[로그인 value 값 지정 jsh]
